WorkSummaryStrapiDemo/Pages/AddSummary.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WorkSummaryStrapiDemo.Extensions;
using WorkSummaryStrapiDemo.Models;
using WorkSummaryStrapiDemo.Services;

namespace WorkSummaryStrapiDemo.Pages
{
    public class AddSummaryModel : PageModel
    {
        private readonly IStrapiService _strapiService;
        private readonly IRedirectionService _redirectionService;

        public AddSummaryModel(IStrapiService strapiService,
            IRedirectionService redirectionService)
        {
            _strapiService = strapiService;
            _redirectionService = redirectionService;
        }

        public AuthCookie Auth { get; set; }
        public string TitleLabel { get; set; }
        public string ContentLabel { get; set; }
        public string SubmitLabel { get; set; }
        public string SummaryId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }

        public async Task<IActionResult> OnGetAsync(string user, string summary)
        {
            var isLogin = await Request.HasLogin(user);
            if (!isLogin)
                return Redirect("Singin");
            Auth = await _strapiService.GetAuthFromPage(Request, user);
            SummaryId = summary;
            if(!string.IsNullOrEmpty(SummaryId))
            {
                var found = await _strapiService.GetSummary(Auth, SummaryId);
                if(found!=null)
                {
                    Title = found.Title;
                    Content = found.Content;
                }
            }
            TitleLabel = await _strapiService.GetLabelAsync("label-title");
            ContentLabel = await _strapiService.GetLabelAsync("label-content");
            SubmitLabel = await _strapiService.GetLabelAsync("label-submit");
            return Page();
        }

        public async Task<ActionResult> OnPostAddSummary(string summaryid, string userid)
        {
            var auth = await _strapiService.GetAuthFromPage(Request, userid);
            var title = Request.Form["title"];
            var content = Request.Form["content"];
            var user = auth.User;
            var created = DateTime.Now;
            var updated = DateTime.Now;
            if (string.IsNullOrEmpty(summaryid))
            {
                await _strapiService.AddSummary(auth,
                    new WorkSummary
                    {
                        Title = title,
                        Content = content,
                        Account = new User { Id = user },
                        Created = created,
                        LastUpdated = updated
                    });
            }
            else 
            {
                await _strapiService.UpdateSummary(auth,
                    new WorkSummary
                    {
                        Id= summaryid,
                        Title = title,
                        Content = content,
                        Account = new User { Id = user },
                        LastUpdated = updated
                    });
            }

            return Redirect(_redirectionService.GetRedirectionUrl($"Index?user={auth.User}"));
        }
    }
}

WorkSummaryStrapiDemo/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace WorkSummaryStrapiDemo.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

WorkSummaryStrapiDemo/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using WorkSummaryStrapiDemo.Extensions;
using WorkSummaryStrapiDemo.Models;
using WorkSummaryStrapiDemo.Services;

namespace WorkSummaryStrapiDemo.Pages
{
    public class IndexModel : PageModel
    {
        private const int PageSize = 10;

        private readonly ILogger<IndexModel> _logger;
        private readonly IStrapiService _strapiService;
        private readonly IRedirectionService _redirectionService;

        public IndexModel(
            ILogger<IndexModel> logger, 
            IStrapiService strapiService,
            IRedirectionService redirectionService)
        {
            _logger = logger;
            _strapiService = strapiService;
            _redirectionService = redirectionService;
            DomainBaseUrl = _redirectionService.GetDomainBaseUrl();
        }

        public string DomainBaseUrl { get; set; }
        public int TotalPages { get; set; }
        public IEnumerable<WorkSummary> Summaries { get; set; }
        public string UserId { get; set; }
        public int CurrentPage { get; set; }
        public string Jwt { get; set; }
        public bool ShowPagination { get; set; }
        public string AddSummaryLabel { get; set; }
        public string PreviousPageLabel { get; set; }
        public string NextPageLabel { get; set; }

        public async Task<IActionResult> OnGetAsync(string user, int currentPage = 0)
        {
            try
            {
                var isLogin = await Request.HasLogin(user);
                if (!isLogin)
                    return Redirect(_redirectionService.GetRedirectionUrl("Signin"));
                var authCookie = await _strapiService.GetAuthFromPage(Request, user);
                UserId = authCookie.User;
                Jwt = authCookie.Jwt;
                CurrentPage = currentPage;
                var totalCount = await _strapiService.GetTotalCount(new AuthCookie { User = UserId, Jwt = Jwt });
                TotalPages = totalCount / PageSize + (totalCount % PageSize > 0 ? 1 : 0);
                Summaries = await _strapiService.GetCurrentPage(new AuthCookie { User = UserId, Jwt = Jwt }, start: CurrentPage * PageSize, limit: PageSize);
                ShowPagination = TotalPages > 1;
                AddSummaryLabel = await _strapiService.GetLabelAsync("label-add-summary");
                PreviousPageLabel = await _strapiService.GetLabelAsync("label-previous-page");
                NextPageLabel = await _strapiService.GetLabelAsync("label-next-page");
                return Page();
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
                return Redirect(_redirectionService.GetRedirectionUrl("Error"));
            }
        }
    }
}

WorkSummaryStrapiDemo/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace WorkSummaryStrapiDemo.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

WorkSummaryStrapiDemo/Pages/Signin.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WorkSummaryStrapiDemo.Models;
using WorkSummaryStrapiDemo.Services;

namespace WorkSummaryStrapiDemo.Pages
{
    public class SigninModel : PageModel
    {
        private readonly IStrapiService _strapiService;
        private readonly IRedirectionService _redirectionService;

        public SigninModel(
            IStrapiService strapiService,
            IRedirectionService redirectionService)
        {
            _strapiService = strapiService;
            _redirectionService = redirectionService;
        }

        public string UserNameLabel { get; set; }
        public string PasswordLabel { get; set; }
        public string SignupLabel { get; set; }
        public string SigninLabel { get; set; }
        public string RememberMeLabel { get; set; }
        public string NoSuchUserLabel { get; set; }
        public string Message { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            UserNameLabel = await _strapiService.GetLabelAsync("label-username");
            PasswordLabel = await _strapiService.GetLabelAsync("label-password");
            SignupLabel = await _strapiService.GetLabelAsync("label-signup");
            SigninLabel = await _strapiService.GetLabelAsync("label-signin");
            RememberMeLabel = await _strapiService.GetLabelAsync("label-rememberme");
            NoSuchUserLabel = await _strapiService.GetLabelAsync("label-no-such-user");

            return Page();
        }

        public async Task<ActionResult> OnPostSignin()
        {
            var username = Request.Form["username"];
            var password = Request.Form["password"];
            var remember = Request.Form["remember"] == "on";
            var user = await _strapiService.FindUserAsync(username, password);
            var succeed = false;
            Message = NoSuchUserLabel;

            if (user != null)
            {
                if (remember)
                {
                    var authorization = await _strapiService.GetAuthorizationAsync();
                    if (authorization != null)
                    {
                        var authCookie = new AuthCookie { User = user.Id, Jwt = authorization.Jwt };
                        Response.SetAuthenticationCookie(authCookie);
                        succeed = true;
                    }
                }
                else 
                {
                    succeed = true;
                }
            }
            
            if(succeed)
            {
                return Redirect(_redirectionService.GetRedirectionUrl($"Index?user={user.Id}"));
            }
            else 
            {
                return Redirect(_redirectionService.GetRedirectionUrl("Signin"));
            }
        }

        public async Task<ActionResult> OnPostSignup()
        {
            return await Task.FromResult(Redirect(_redirectionService.GetRedirectionUrl("Signup")));
        }
    }
}

WorkSummaryStrapiDemo/Pages/Signup.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WorkSummaryStrapiDemo.Services;

namespace WorkSummaryStrapiDemo.Pages
{
    public class SignupModel : PageModel
    {
        private readonly IStrapiService _strapiService;
        private readonly IRedirectionService _redirectionService;

        public SignupModel(IStrapiService strapiService,
            IRedirectionService redirectionService)
        {
            _strapiService = strapiService;
            _redirectionService = redirectionService;
            DomainBaseUrl = _redirectionService.GetDomainBaseUrl();
        }

        public string DomainBaseUrl { get; set; }
        public string UserNameLabel { get; set; }
        public string PasswordLabel { get; set; }
        public string ConfirmPasswordLabel { get; set; }
        public string SignupLabel { get; set; }
        public string UserExistedLabel { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            UserNameLabel = await _strapiService.GetLabelAsync("label-username");
            PasswordLabel = await _strapiService.GetLabelAsync("label-password");
            SignupLabel = await _strapiService.GetLabelAsync("label-signup");
            ConfirmPasswordLabel = await _strapiService.GetLabelAsync("label-confirmpassword");
            UserExistedLabel = await _strapiService.GetLabelAsync("label-user-existed");

            return Page();
        }

        public async Task<ActionResult> OnPostSignup()
        {
            var username = Request.Form["username"];
            var password = Request.Form["password"];

            var result = await _strapiService.AddUser(username, password);
            if(result)
            {
                return Redirect(_redirectionService.GetRedirectionUrl("Signin"));
            }
            else
            {
                return Redirect(_redirectionService.GetRedirectionUrl("Signup"));
            }
        }
    }
}

WorkSummaryStrapiDemo/Pages/AddSummary.cshtml
@page
@model WorkSummaryStrapiDemo.Pages.AddSummaryModel
@{
    ViewData["Title"] = "AddSummary";
}

<script src='https://cdn.tiny.cloud/1/x016fan6dgubn7hq910v239eujx38pc9xi2j0pyq1vnobxb7/tinymce/5/tinymce.min.js' referrerpolicy="origin">
</script>
<script>
    tinymce.init({
        selector: '#content'
    });
</script>

<div class="summary-wrapper">
    <form method="post">
        <div class="form-group summary-group">
            <label>@Model.TitleLabel</label>
            <input name="title" type="text" placeholder="@Model.TitleLabel" value="@Model.Title" />
        </div>
        <div class="form-group summary-group">
            <label>@Model.ContentLabel</label>
            <textarea id="content" name="content" type="password" placeholder="@Model.ContentLabel">@Model.Content</textarea>
        </div>
        <div class="form-group login-wrapper">
            <button type="submit" asp-page-handler="AddSummary" asp-route-summaryid="@Model.SummaryId" asp-route-userid="@Model.Auth.User" class="btn btn-primary">@Model.SubmitLabel</button>
        </div>
    </form>
</div>

WorkSummaryStrapiDemo/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}


<div class="container">
    <div class="row right-wrapper">
        <a href="@Model.DomainBaseUrl/AddSummary?user=@Model.UserId" class="btn btn-primary">
            <i class="fas fa-plus"></i>
            @Model.AddSummaryLabel
        </a>
    </div>
    <div class="row central-wrapper">
        @foreach(var summary in Model.Summaries)
        {
            <div class="work-summary">
                <a href="@Model.DomainBaseUrl/AddSummary?summary=@summary.Id">@summary.Title</a>
                <a href="@Model.DomainBaseUrl/AddSummary?summary=@summary.Id">
                    <i class="fas fa-pen"></i>
                </a>
            </div>
        }
    </div>
    @if (Model.ShowPagination)
    {
        var previousPageClass = Model.CurrentPage <= 0 ? "disabled" : string.Empty;
        var nextPageClass = Model.CurrentPage >= Model.TotalPages - 1 ? "disabled" : string.Empty;
        <div class="row central-wrapper">
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    <li class="page-item @previousPageClass"><a class="page-link" href="@Model.DomainBaseUrl/Index?user=@Model.UserId&currentPage=@(Model.CurrentPage-1)">@Model.PreviousPageLabel</a></li>
                    @for (var i = 0; i < Model.TotalPages; i++)
                    {
                        var active = i == Model.CurrentPage ? "active" : string.Empty;
                        <li class="page-item @active"><a class="page-link" href="@Model.DomainBaseUrl/Index?user=@Model.UserId&currentPage=@i">@(i+1)</a></li>
                    }
                    <li class="page-item @nextPageClass"><a class="page-link" href="@Model.DomainBaseUrl/Index?user=@Model.UserId&currentPage=@(Model.CurrentPage+1)">@Model.NextPageLabel</a></li>
                </ul>
            </nav>
        </div>
    }
</div>

WorkSummaryStrapiDemo/Pages/Signin.cshtml
@page
@model WorkSummaryStrapiDemo.Pages.SigninModel
@{
    ViewData["Title"] = "Signin";
}

<div class="login-wrapper">
    <form method="post">
        <div class="form-group">
            <label class="login-labels">@Model.UserNameLabel</label>
            <input name="username" type="text" placeholder="@Model.UserNameLabel" />
        </div>
        <div class="form-group">
            <label class="login-labels">@Model.PasswordLabel</label>
            <input name="password" type="password" placeholder="@Model.PasswordLabel" />
        </div>
        <div class="form-check">
            <input name="remember" type="checkbox" />
            <label>@Model.RememberMeLabel</label>
        </div>
        <div class="form-group login-wrapper">
            <button type="submit" asp-page-handler="Signin" class="btn btn-primary login-button">@Model.SigninLabel</button>
            <button type="submit" asp-page-handler="Signup" class="btn btn-secondary login-button">@Model.SignupLabel</button>
        </div>
    </form>
</div>

WorkSummaryStrapiDemo/Pages/Signup.cshtml
@page
@model WorkSummaryStrapiDemo.Pages.SignupModel
@{
    ViewData["Title"] = "Signup";
}

<div id="signup-wrapper" class="login-wrapper" data-domain-base="@Model.DomainBaseUrl">
    <form method="post">
        <div class="form-group">
            <label class="login-labels">@Model.UserNameLabel</label>
            <input name="username" type="text" placeholder="@Model.UserNameLabel" data-message="@Model.UserExistedLabel" />
        </div>
        <div class="form-group">
            <label class="login-labels">@Model.PasswordLabel</label>
            <input name="password" type="password" placeholder="@Model.PasswordLabel" />
        </div>
        <div class="form-group login-wrapper">
            <button type="submit" asp-page-handler="Signup" class="btn btn-primary login-button">@Model.SignupLabel</button>
        </div>
    </form>
</div>